class AfricanCities {
  static const List<String> popularCities = [
    "Douala (Cameroun)",
    "Yaoundé (Cameroun)",
    "Bafoussam (Cameroun)",
    "Garoua (Cameroun)",
    "Bamenda (Cameroun)",
    "Maroua (Cameroun)",
    "Kribi (Cameroun)",
    "Limbé (Cameroun)",
    "Abidjan (Côte d'Ivoire)",
    "Yamoussoukro (Côte d'Ivoire)",
    "Bouaké (Côte d'Ivoire)",
    "Dakar (Sénégal)",
    "Saint-Louis (Sénégal)",
    "Libreville (Gabon)",
    "Port-Gentil (Gabon)",
    "Brazzaville (Congo)",
    "Pointe-Noire (Congo)",
    "Kinshasa (RDC)",
    "Lubumbashi (RDC)",
    "Goma (RDC)",
    "Lomé (Togo)",
    "Cotonou (Bénin)",
    "Porto-Novo (Bénin)",
    "Ouagadougou (Burkina Faso)",
    "Niamey (Niger)",
    "N'Djamena (Tchad)",
    "Bamako (Mali)",
    "Bangui (RCA)",
    "Kigali (Rwanda)",
    "Bujumbura (Burundi)",
    "Luanda (Angola)",
    "Malabo (Guinée Équatoriale)",
    "Casablanca (Maroc)",
    "Rabat (Maroc)",
    "Tunis (Tunisie)",
    "Alger (Algérie)",
    "Nairobi (Kenya)",
    "Johannesburg (Afrique du Sud)",
    "Le Cap (Afrique du Sud)",
  ];

  static const List<String> allCities = [
    "Abidjan (Côte d'Ivoire)",
    "Abuja (Nigeria)",
    "Accra (Ghana)",
    "Addis-Abeba (Éthiopie)",
    "Alger (Algérie)",
    "Antananarivo (Madagascar)",
    "Asmara (Érythrée)",
    "Bafoussam (Cameroun)",
    "Bamako (Mali)",
    "Bamenda (Cameroun)",
    "Bangui (RCA)",
    "Banjul (Gambie)",
    "Brazzaville (Congo)",
    "Bujumbura (Burundi)",
    "Casablanca (Maroc)",
    "Conakry (Guinée)",
    "Cotonou (Bénin)",
    "Dakar (Sénégal)",
    "Dar es Salam (Tanzanie)",
    "Djibouti (Djibouti)",
    "Douala (Cameroun)",
    "Freetown (Sierra Leone)",
    "Gaborone (Botswana)",
    "Garoua (Cameroun)",
    "Gitega (Burundi)",
    "Goma (RDC)",
    "Harare (Zimbabwe)",
    "Johannesburg (Afrique du Sud)",
    "Kampala (Ouganda)",
    "Karthoum (Soudan)",
    "Kigali (Rwanda)",
    "Kinshasa (RDC)",
    "Kribi (Cameroun)",
    "Le Cap (Afrique du Sud)",
    "Libreville (Gabon)",
    "Lilongwe (Malawi)",
    "Limbé (Cameroun)",
    "Lomé (Togo)",
    "Luanda (Angola)",
    "Lubumbashi (RDC)",
    "Lusaka (Zambie)",
    "Malabo (Guinée Équatoriale)",
    "Maputo (Mozambique)",
    "Maroua (Cameroun)",
    "Maseru (Lesotho)",
    "Mbabane (Eswatini)",
    "Mogadiscio (Somalie)",
    "Monrovia (Libéria)",
    "N'Djamena (Tchad)",
    "Nairobi (Kenya)",
    "Niamey (Niger)",
    "Nouakchott (Mauritanie)",
    "Ouagadougou (Burkina Faso)",
    "Pointe-Noire (Congo)",
    "Port-Gentil (Gabon)",
    "Port-Louis (Maurice)",
    "Porto-Novo (Bénin)",
    "Rabat (Maroc)",
    "Saint-Louis (Sénégal)",
    "Tanger (Maroc)",
    "Tunis (Tunisie)",
    "Victoria (Seychelles)",
    "Windhoek (Namibie)",
    "Yamoussoukro (Côte d'Ivoire)",
    "Yaoundé (Cameroun)",
  ];
}
