[providers]
python = "3.12"

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "libpqxx"]

[phases.install]
cmds = ["python3 -m pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["python3 backend/manage.py collectstatic --noinput"]

[start]
cmd = "python3 backend/manage.py migrate && daphne -b 0.0.0.0 -p ${PORT:-8000} config.asgi:application"
