# Generated by Django 5.0.14 on 2026-09-15 07:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('category', models.CharField(default='lifestyle', max_length=50)),
            ],
            options={
                'verbose_name': "Centre d'intérêt",
                'verbose_name_plural': "Centres d'intérêt",
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], max_length=10)),
                ('seeking', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], default='female', max_length=10)),
                ('intention', models.CharField(choices=[('serious', 'Relation sérieuse'), ('casual', 'Rencontre décontractée'), ('friendship', 'Amitié'), ('networking', 'Réseautage professionnel'), ('undecided', 'Je ne sais pas encore')], default='serious', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('city', models.CharField(default='Yaoundé', max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(default=3.848)),
                ('longitude', models.FloatField(default=11.5021)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(default='none', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('is_incognito', models.BooleanField(default=False)),
                ('hide_distance', models.BooleanField(default=False)),
                ('hide_age', models.BooleanField(default=False)),
                ('personality_answers', models.JSONField(blank=True, default=dict)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField(default=18)),
                ('max_age', models.PositiveSmallIntegerField(default=55)),
                ('max_distance_km', models.PositiveIntegerField(default=50)),
                ('preferred_genders', models.JSONField(default=list)),
                ('preferred_intentions', models.JSONField(default=list)),
                ('verified_only', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='profiles/photos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='profiles/thumbnails/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.interest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile', 'interest')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='profiles', through='profiles.ProfileInterest', to='profiles.interest'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['latitude', 'longitude'], name='profiles_pr_latitud_6b6a14_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='profiles_pr_gender_fc2e15_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['intention'], name='profiles_pr_intenti_28a1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_premium'], name='profiles_pr_is_prem_2a9ae4_idx'),
        ),
    ]
