# Generated by Django 5.0.14 on 2026-09-15 07:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('price_xaf', models.PositiveIntegerField(help_text='Prix en FCFA (XAF)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Formule d'abonnement",
                'verbose_name_plural': "Formules d'abonnement",
                'ordering': ['price_xaf'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.plan')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='profiles.profile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_xaf', models.PositiveIntegerField()),
                ('provider', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('mock', 'Mode Test / Demo')], max_length=10)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation USSD'), ('success', 'Succès'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.plan')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
